# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DictPicInfoUi.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(850, 241)
        self.layoutWidget = QtWidgets.QWidget(widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 844, 238))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.dict_1 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dict_1.sizePolicy().hasHeightForWidth())
        self.dict_1.setSizePolicy(sizePolicy)
        self.dict_1.setMinimumSize(QtCore.QSize(204, 114))
        self.dict_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_1.setObjectName("dict_1")
        self.verticalLayout_12.addWidget(self.dict_1)
        self.dict_1_info = QtWidgets.QLabel(self.layoutWidget)
        self.dict_1_info.setMinimumSize(QtCore.QSize(204, 114))
        self.dict_1_info.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_1_info.setObjectName("dict_1_info")
        self.verticalLayout_12.addWidget(self.dict_1_info)
        self.horizontalLayout_7.addLayout(self.verticalLayout_12)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.dict_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dict_2.sizePolicy().hasHeightForWidth())
        self.dict_2.setSizePolicy(sizePolicy)
        self.dict_2.setMinimumSize(QtCore.QSize(204, 114))
        self.dict_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_2.setObjectName("dict_2")
        self.verticalLayout_13.addWidget(self.dict_2)
        self.dict_2_info = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dict_2_info.sizePolicy().hasHeightForWidth())
        self.dict_2_info.setSizePolicy(sizePolicy)
        self.dict_2_info.setMinimumSize(QtCore.QSize(204, 114))
        self.dict_2_info.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_2_info.setObjectName("dict_2_info")
        self.verticalLayout_13.addWidget(self.dict_2_info)
        self.horizontalLayout_7.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.dict_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dict_3.sizePolicy().hasHeightForWidth())
        self.dict_3.setSizePolicy(sizePolicy)
        self.dict_3.setMinimumSize(QtCore.QSize(204, 114))
        self.dict_3.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_3.setObjectName("dict_3")
        self.verticalLayout_14.addWidget(self.dict_3)
        self.dict_3_info = QtWidgets.QLabel(self.layoutWidget)
        self.dict_3_info.setMinimumSize(QtCore.QSize(204, 114))
        self.dict_3_info.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_3_info.setObjectName("dict_3_info")
        self.verticalLayout_14.addWidget(self.dict_3_info)
        self.horizontalLayout_7.addLayout(self.verticalLayout_14)
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.dict_4 = QtWidgets.QLabel(self.layoutWidget)
        self.dict_4.setMinimumSize(QtCore.QSize(204, 114))
        self.dict_4.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_4.setObjectName("dict_4")
        self.verticalLayout_15.addWidget(self.dict_4)
        self.dict_4_info = QtWidgets.QLabel(self.layoutWidget)
        self.dict_4_info.setAlignment(QtCore.Qt.AlignCenter)
        self.dict_4_info.setObjectName("dict_4_info")
        self.verticalLayout_15.addWidget(self.dict_4_info)
        self.horizontalLayout_7.addLayout(self.verticalLayout_15)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.dict_1.setText(_translate("widget", "塑件1——图片"))
        self.dict_1_info.setText(_translate("widget", "塑件1——信息"))
        self.dict_2.setText(_translate("widget", "塑件2——图片"))
        self.dict_2_info.setText(_translate("widget", "塑件2——信息"))
        self.dict_3.setText(_translate("widget", "塑件3——图片"))
        self.dict_3_info.setText(_translate("widget", "塑件3——信息"))
        self.dict_4.setText(_translate("widget", "塑件4——图片"))
        self.dict_4_info.setText(_translate("widget", "塑件4——信息"))

