
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindowUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1618, 941)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(81)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1600, 600))
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget1 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget1.sizePolicy().hasHeightForWidth())
        self.widget1.setSizePolicy(sizePolicy)
        self.widget1.setMinimumSize(QtCore.QSize(140, 0))
        self.widget1.setAutoFillBackground(False)
        self.widget1.setStyleSheet("background-color: rgb(233, 131, 0);\n"
"")
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(10, -1, 10, -1)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 65))
        self.widget_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.button_camera = QtWidgets.QToolButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.button_camera.sizePolicy().hasHeightForWidth())
        self.button_camera.setSizePolicy(sizePolicy)
        self.button_camera.setMinimumSize(QtCore.QSize(82, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_camera.setFont(font)
        self.button_camera.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.button_camera.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_camera.setStyleSheet("QToolButton {\n"
"    background-color: white;\n"
"    border-color: rgb(255, 255, 255);\n"
"    min-width: 80px;\n"
"    height:30px;\n"
"    min-height:25px;\n"
"    color:rgb(233, 131, 0);\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/window_icon/camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_camera.setIcon(icon)
        self.button_camera.setIconSize(QtCore.QSize(76, 76))
        self.button_camera.setCheckable(False)
        self.button_camera.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.button_camera.setAutoRaise(True)
        self.button_camera.setObjectName("button_camera")
        self.verticalLayout_4.addWidget(self.button_camera)
        self.verticalLayout.addWidget(self.widget_2)
        spacerItem = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.widget_3 = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 65))
        self.widget_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_modify = QtWidgets.QToolButton(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.button_modify.sizePolicy().hasHeightForWidth())
        self.button_modify.setSizePolicy(sizePolicy)
        self.button_modify.setMinimumSize(QtCore.QSize(82, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_modify.setFont(font)
        self.button_modify.setStyleSheet("QToolButton {\n"
"    background-color: white;\n"
"    border-color: rgb(255, 255, 255);\n"
"qproperty-icon: url(:/icon/window_icon/设置1.svg);\n"
"    min-width: 80px;\n"
"    height:30px;\n"
"    min-height:25px;\n"
"    color:rgb(233, 131, 0);\n"
"}\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/window_icon/设置1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icon/window_icon/设置w.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon1.addPixmap(QtGui.QPixmap(":/icon/window_icon/设置w.svg"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.button_modify.setIcon(icon1)
        self.button_modify.setIconSize(QtCore.QSize(76, 76))
        self.button_modify.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.button_modify.setAutoRaise(True)
        self.button_modify.setObjectName("button_modify")
        self.horizontalLayout_3.addWidget(self.button_modify)
        self.verticalLayout.addWidget(self.widget_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.widget_4 = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 65))
        self.widget_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.button_show_detected = QtWidgets.QToolButton(self.widget_4)
        self.button_show_detected.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.button_show_detected.sizePolicy().hasHeightForWidth())
        self.button_show_detected.setSizePolicy(sizePolicy)
        self.button_show_detected.setMinimumSize(QtCore.QSize(82, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_show_detected.setFont(font)
        self.button_show_detected.setStyleSheet("QToolButton {\n"
"    background-color: white;\n"
"    border-color: rgb(255, 255, 255);\n"
"    min-width: 80px;\n"
"    height:30px;\n"
"    min-height:25px;\n"
"qproperty-icon: url(:/icon/window_icon/切换1.svg);\n"
"    color:rgb(233, 131, 0);\n"
"}\n"
"QToolButton:disabled {\n"
"    background-color:rgb(240, 240, 240);}\n"
"QToolButton:!enabled {\n"
"    background-color:rgb(240, 240, 240);\n"
"}\n"
"QToolButton:on{\n"
"    color: rgb(255, 255, 255);\n"
"    qproperty-icon: url(:/icon/window_icon/切换开.svg);\n"
"    background-color: rgb(233, 131, 0);\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/window_icon/切换1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/icon/window_icon/切换开.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.button_show_detected.setIcon(icon2)
        self.button_show_detected.setIconSize(QtCore.QSize(76, 76))
        self.button_show_detected.setShortcut("")
        self.button_show_detected.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.button_show_detected.setAutoRaise(True)
        self.button_show_detected.setObjectName("button_show_detected")
        self.horizontalLayout_5.addWidget(self.button_show_detected)
        self.verticalLayout.addWidget(self.widget_4)
        spacerItem2 = QtWidgets.QSpacerItem(20, 120, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.widget_5 = QtWidgets.QWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(0, 56))
        self.widget_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_6.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_6.setSpacing(2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.button_exit = QtWidgets.QToolButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(self.button_exit.sizePolicy().hasHeightForWidth())
        self.button_exit.setSizePolicy(sizePolicy)
        self.button_exit.setMinimumSize(QtCore.QSize(82, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.button_exit.setFont(font)
        self.button_exit.setStyleSheet("QToolButton {\n"
"    background-color: white;\n"
"    border-color: rgb(255, 255, 255);\n"
"\n"
"    min-width: 80px;\n"
"    height:30px;\n"
"    min-height:25px;\n"
"    color:rgb(233, 131, 0);\n"
"}\n"
"QPushButton:pressed{\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(233, 131, 0);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/window_icon/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_exit.setIcon(icon3)
        self.button_exit.setIconSize(QtCore.QSize(76, 76))
        self.button_exit.setCheckable(False)
        self.button_exit.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.button_exit.setAutoRaise(True)
        self.button_exit.setObjectName("button_exit")
        self.horizontalLayout_6.addWidget(self.button_exit)
        self.verticalLayout.addWidget(self.widget_5)
        self.horizontalLayout.addWidget(self.widget1)
        self.frame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("")
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget_21 = QtWidgets.QWidget(self.frame)
        self.widget_21.setStyleSheet("background-color: rgb(233, 131, 0);")
        self.widget_21.setObjectName("widget_21")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_21)
        self.verticalLayout_3.setContentsMargins(9, -1, 9, 9)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.camera = QtWidgets.QLabel(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(32)
        sizePolicy.setHeightForWidth(self.camera.sizePolicy().hasHeightForWidth())
        self.camera.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(36)
        font.setBold(True)
        font.setWeight(75)
        self.camera.setFont(font)
        self.camera.setStyleSheet("background-color: rgb(233, 131, 0);\n"
"color: rgb(255, 255, 255);")
        self.camera.setTextFormat(QtCore.Qt.AutoText)
        self.camera.setAlignment(QtCore.Qt.AlignCenter)
        self.camera.setObjectName("camera")
        self.verticalLayout_3.addWidget(self.camera)
        self.label_2 = QtWidgets.QLabel(self.widget_21)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout_2.addWidget(self.widget_21)
        self.horizontalLayout.addWidget(self.frame)
        self.switch_frame = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.switch_frame.sizePolicy().hasHeightForWidth())
        self.switch_frame.setSizePolicy(sizePolicy)
        self.switch_frame.setMinimumSize(QtCore.QSize(244, 245))
        self.switch_frame.setStyleSheet("background-color: rgb(233, 131, 0);")
        self.switch_frame.setObjectName("switch_frame")
        self.horizontalLayout.addWidget(self.switch_frame)
        self.verticalLayout_2.addWidget(self.widget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Plastic Pieces Recognition And Location"))
        self.button_camera.setText(_translate("MainWindow", "Start Detect"))
        self.button_modify.setText(_translate("MainWindow", "Modify Area"))
        self.button_show_detected.setText(_translate("MainWindow", "Recognized\n"
" Picture"))
        self.button_exit.setText(_translate("MainWindow", "Close"))
        self.camera.setText(_translate("MainWindow", "UNOPENED"))
        self.label_2.setText(_translate("MainWindow", "Real-Time Picture"))
import resource_rc
