# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModifyUi_Vertical.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(251, 793)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(10, 10, 221, 771))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 40, 194, 691))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.high_limit_value = QtWidgets.QLabel(self.layoutWidget)
        self.high_limit_value.setMinimumSize(QtCore.QSize(40, 0))
        self.high_limit_value.setMaximumSize(QtCore.QSize(40, 16777215))
        self.high_limit_value.setObjectName("high_limit_value")
        self.horizontalLayout.addWidget(self.high_limit_value)
        self.high_limit_slider = QtWidgets.QSlider(self.layoutWidget)
        self.high_limit_slider.setMaximum(20000)
        self.high_limit_slider.setOrientation(QtCore.Qt.Vertical)
        self.high_limit_slider.setObjectName("high_limit_slider")
        self.horizontalLayout.addWidget(self.high_limit_slider)
        spacerItem = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.low_limit_slider = QtWidgets.QSlider(self.layoutWidget)
        self.low_limit_slider.setMinimum(50)
        self.low_limit_slider.setOrientation(QtCore.Qt.Vertical)
        self.low_limit_slider.setObjectName("low_limit_slider")
        self.horizontalLayout.addWidget(self.low_limit_slider)
        self.low_limit_value = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.low_limit_value.sizePolicy().hasHeightForWidth())
        self.low_limit_value.setSizePolicy(sizePolicy)
        self.low_limit_value.setMinimumSize(QtCore.QSize(40, 0))
        self.low_limit_value.setMaximumSize(QtCore.QSize(40, 16777215))
        self.low_limit_value.setObjectName("low_limit_value")
        self.horizontalLayout.addWidget(self.low_limit_value)
        self.max_high_limit = QtWidgets.QLabel(self.frame)
        self.max_high_limit.setGeometry(QtCore.QRect(60, 20, 41, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.max_high_limit.setFont(font)
        self.max_high_limit.setObjectName("max_high_limit")
        self.min_low_limit = QtWidgets.QLabel(self.frame)
        self.min_low_limit.setGeometry(QtCore.QRect(140, 730, 31, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.min_low_limit.setFont(font)
        self.min_low_limit.setObjectName("min_low_limit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.high_limit_value.setText(_translate("Form", "TextLabel"))
        self.low_limit_value.setText(_translate("Form", "TextLabel"))
        self.max_high_limit.setText(_translate("Form", "200000"))
        self.min_low_limit.setText(_translate("Form", " 50"))
